### ISSUE TITLE
Support stale-while-revalidate in FreshnessChecker

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#1400] opened 2024-07-30 16:57 UTC
We should support a policy where ZiplineLoader loads potentially-stale local code while downloading fresh code. This mechanism should be integrated into FreshnessChecker, which could determine if the potentially-stale code is fresh enough to launch.

**Comment by JakeWharton** [comment] 2024-07-30 17:02
Dupe of #1258?

**Closed as not planned** 2024-09-03 16:54 UTC
Labels: loader
