### ISSUE TITLE
Signing tests are flaky

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/zipline#970] opened 2023-05-04 00:29 UTC
```
> Task :zipline-loader:macosX64Test

app.cash.zipline.loader.internal.EcdsaP256Test.testVerificationWithWycheproofVectors[macosX64] FAILED
    okio.FileNotFoundException at /opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:25

app.cash.zipline.loader.internal.tink.subtle.Ed25519SignTest.testSigningWithWycheproofVectors[macosX64] FAILED
    okio.FileNotFoundException at /opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:25

app.cash.zipline.loader.internal.tink.subtle.Ed25519VerifyTest.testVerificationWithWycheproofVectors[macosX64] FAILED
    okio.FileNotFoundException at /opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:25

121 tests completed, 3 failed
```
Seen multiple times on CI.

**Comment by swankjesse** [comment] 2023-05-18 21:00
Duplicate of https://github.com/cashapp/zipline/issues/763

**Closed as completed by swankjesse** 2023-05-18 21:00 UTC
